-- Snowflake remains external. Set this to an existing database before running.
-- This script intentionally never creates or hard-codes a database.
SET PROJECT_DATABASE = '<existing_project_database>';
SET BRONZE_SCHEMA = $PROJECT_DATABASE || '.BRONZE';
SET SILVER_SCHEMA = $PROJECT_DATABASE || '.SILVER';
SET GOLD_SCHEMA = $PROJECT_DATABASE || '.GOLD';
SET OBT_SCHEMA = $PROJECT_DATABASE || '.OBT';

CREATE SCHEMA IF NOT EXISTS IDENTIFIER($BRONZE_SCHEMA);
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($SILVER_SCHEMA);
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($GOLD_SCHEMA);
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($OBT_SCHEMA);
