-- Snowflake remains external. Set this to an existing database before running.
-- This script intentionally never creates or hard-codes a database.
SET PROJECT_DATABASE = 'S_CDATOS_PSET2';
SET BRONZE_SCHEMA = $PROJECT_DATABASE || '.S_CDATOS_PSET2_BRONZE';
SET SILVER_SCHEMA = $PROJECT_DATABASE || '.S_CDATOS_PSET2_SILVER';
SET GOLD_SCHEMA = $PROJECT_DATABASE || '.S_CDATOS_PSET2_GOLD';
SET OBT_SCHEMA = $PROJECT_DATABASE || '.S_CDATOS_PSET2_OBT';

CREATE SCHEMA IF NOT EXISTS IDENTIFIER($BRONZE_SCHEMA);
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($SILVER_SCHEMA);
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($GOLD_SCHEMA);
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($OBT_SCHEMA);
