-- In the same worksheet/session as 001, use the caller-supplied existing DB.
USE DATABASE IDENTIFIER($PROJECT_DATABASE);
USE SCHEMA IDENTIFIER($BRONZE_SCHEMA);
CREATE STAGE IF NOT EXISTS SMART_ARCHIVE_STAGE
  FILE_FORMAT = SMART_CSV_FORMAT;
ALTER STAGE SMART_ARCHIVE_STAGE SET FILE_FORMAT = SMART_CSV_FORMAT;
