-- In the same worksheet/session as 001, use the caller-supplied existing DB.
USE DATABASE IDENTIFIER($PROJECT_DATABASE);
USE SCHEMA BRONZE;
CREATE STAGE IF NOT EXISTS SMART_ARCHIVE_STAGE
  FILE_FORMAT = SMART_CSV_FORMAT;
