-- Run in the same worksheet/session as 001_database_and_schemas.sql.
-- Bronze keeps source values unchanged inside RAW_RECORD; dbt performs typing.
USE DATABASE IDENTIFIER($PROJECT_DATABASE);
USE SCHEMA IDENTIFIER($BRONZE_SCHEMA);

CREATE TABLE IF NOT EXISTS SMART_2018_RAW (
  SOURCE_ARCHIVE VARCHAR,
  SOURCE_FILE VARCHAR,
  SOURCE_ROW NUMBER,
  SOURCE_DATE DATE,
  SOURCE_SHA256 VARCHAR,
  RAW_RECORD VARIANT,
  INGESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS SMART_2019_RAW LIKE SMART_2018_RAW;
CREATE TABLE IF NOT EXISTS SSD_FAILURE_LABEL_RAW LIKE SMART_2018_RAW;
