-- Select an existing Snowflake database before running this script.
-- Replace the placeholder with its exact unquoted identifier.
SET PROJECT_DATABASE = '<existing_project_database>';
SET BRONZE_SCHEMA = $PROJECT_DATABASE || '.S_CDATOS_BRONZE';
SET SILVER_SCHEMA = $PROJECT_DATABASE || '.S_CDATOS_SILVER';
SET GOLD_SCHEMA = $PROJECT_DATABASE || '.S_CDATOS_GOLD';

CREATE SCHEMA IF NOT EXISTS IDENTIFIER($BRONZE_SCHEMA);
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($SILVER_SCHEMA);
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($GOLD_SCHEMA);
