-- Run in the same Snowflake worksheet/session as 001_schemas.sql.
USE DATABASE IDENTIFIER($PROJECT_DATABASE);
USE SCHEMA S_CDATOS_BRONZE;

CREATE FILE FORMAT IF NOT EXISTS YELLOW_TAXI_PARQUET_FORMAT TYPE = PARQUET;
CREATE STAGE IF NOT EXISTS YELLOW_TAXI_STAGE
  FILE_FORMAT = YELLOW_TAXI_PARQUET_FORMAT;
